name: sleepproject
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - mne
  - matplotlib
  - seaborn
  - tqdm
  - pip
  - pip:
      - yasa
      - pyedflib
      - tensorflow
